version: '2.0'
services:
  redis:
    image: redis:alpine
    restart: always
    container_name: pimcore-redis

  db:
    image: mariadb:10.1
    container_name: pimcore-mariadb
    restart: always
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
    volumes:
      - pimcore-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    build:
      context: phpmyadmin
      dockerfile: Dockerfile
    container_name: pimcore-phpmyadmin
    restart: always
    ports:
      - '2002:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ROOT

  pimcore:
    depends_on:
      - db
      - redis
    build:
      context: pimcore-app
      dockerfile: Dockerfile
    container_name: pimcore-app
    restart: always
    volumes:
      - pimcore-app:/var/www/html
    environment:
     - PIMCORE_INSTALL_ADMIN_USERNAME=admin
     - PIMCORE_INSTALL_ADMIN_PASSWORD=admin
     - PIMCORE_INSTALL_MYSQL_HOST_SOCKET=db
     - PIMCORE_INSTALL_MYSQL_USERNAME=pimcore
     - PIMCORE_INSTALL_MYSQL_PASSWORD=pimcore
     - PIMCORE_INSTALL_MYSQL_DATABASE=pimcore
     - PIMCORE_INSTALL_MYSQL_PORT=3306
    ports:
     - "2000:80"
     - "2001:443"
    links:
     - db:db
     - redis:redis

volumes:
  pimcore-database:
  pimcore-app: